// @vitest-environment jsdom
import { act, cleanup, renderHook } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { createDefaultScenario } from '../lib/scenario'
import { cardEntriesForCycle } from '../lib/cardCycleView'
import { calculateCreditCardSummary } from '../lib/creditCards'
import { createPaidInvoiceSnapshot } from '../lib/cardCycleAccounting'
import { readRepositoryDocument, writeRepositoryDocument } from '../data/repository'
import { repositoryRevision } from '../data/repositoryCommand'
import { reviewCardCalendar, saveCardCalendar } from '../data/cardCalendarCommand'
import { repositoryToBackupV9, backupV9ToRepository, inspectBackupPayload } from '../data/backupV7'
import { reviewCardImport, applyCardImport } from '../data/cardImportCommand'
import { parseSpreadsheetReport } from '../lib/cardImport'
import { useFinancas } from './useFinancas'
import { historyCorrectionRows } from '../data/historyCorrections'
import type { CreditCardEntry } from '../types'

beforeEach(() => localStorage.clear())
afterEach(() => { cleanup(); vi.restoreAllMocks() })

function seed() {
  const scenario = createDefaultScenario('Atual')
  scenario.salaryNet = 5000; scenario.deductions = []; scenario.costs = []; scenario.wants = []; scenario.plannedInvestmentAmount = 0
  const hering: CreditCardEntry = { id: 'hering-1', accountId: 'nu', cardName: 'Nu', cycle: 'current', dueMonth: '2026-11', spendingMonth: '2026-10',
    description: 'rg comercio hering', purchaseDate: '27/09', amount: 50, personalAmount: 50, remainingAmount: 200, installmentCurrent: 1, installmentTotal: 5 }
  const umbro: CreditCardEntry = { ...hering, id: 'umbro-1', accountId: 'ml', cardName: 'ML', description: 'umbro pro', purchaseDate: '16/09', amount: 123.30, personalAmount: 123.30, remainingAmount: 246.60, installmentTotal: 3, budgetArea: 'desejos' }
  writeRepositoryDocument({ schemaVersion: 7, updatedAt: '2026-10-08T18:00:00Z', appliedOperations: ['pay-invoice:nu:2026-11'], collections: {
    scenarios: [scenario], activeScenarioId: scenario.id, activeCycle: { month: '2026-10', salaryHintDay: 30, cardDueHintDay: 5 },
    cardSettings: { currentDueMonth: '2026-11', paymentDate: '05/11', personalSpendingLimit: 1500 },
    cardAccounts: [{ id: 'nu', name: 'Nu', currentDueMonth: '2026-12', dueDay: 13, closingDay: 4, limit: 0 },
      { id: 'ml', name: 'ML', currentDueMonth: '2026-11', dueDay: 16, closingDay: 10, limit: 0 }],
    cardEntries: [{ ...hering, id: 'hering-2', installmentCurrent: 2, dueMonth: '2026-12', spendingMonth: '2026-11', remainingAmount: 150 },
      { ...hering, id: 'hering-3', installmentCurrent: 3, cycle: 'next', dueMonth: '2027-01', spendingMonth: '2026-12', remainingAmount: 100, sourceEntryId: 'hering-2', autoGenerated: true }, umbro,
      { ...umbro, id: 'umbro-2', installmentCurrent: 2, cycle: 'next', dueMonth: '2026-12', spendingMonth: '2026-11', remainingAmount: 123.30, sourceEntryId: 'umbro-1', autoGenerated: true }],
    cardPaidInvoices: [{ ...createPaidInvoiceSnapshot({ accountId: 'nu', currentDueMonth: '2026-11', entries: [hering], total: 50, personalTotal: 50, paidAt: '2026-10-08T18:45:24Z' }), id: 'invoice-nu-2026-11' }],
    actuals: [{ month: '2026-10', costs: {}, wants: {}, extraIncome: [], extraExpenses: [], paycheck: { amount: 5000, payrollInvestment: 0, employerInvestment: 0 } }],
  } })
}
const nuDraft = { accountId: 'nu', openDueMonth: '2026-11', dueMonthOffset: 1 as const, includePaidInvoices: true, reason: 'A parcela 1 venceu em outubro' }
const mlDraft = { accountId: 'ml', openDueMonth: '2026-10', dueMonthOffset: 0 as const, includePaidInvoices: false, reason: 'A fatura aberta vence em outubro' }
function correct() {
  expect(saveCardCalendar(nuDraft, repositoryRevision()).ok).toBe(true)
  expect(saveCardCalendar(mlDraft, repositoryRevision()).ok).toBe(true)
}

it('corrige Nubank e ML juntos sem perder pagamentos, parcelas, IDs ou calendário no backup', () => {
  seed()
  const before = readRepositoryDocument()
  const original = JSON.stringify(before)
  reviewCardCalendar(before, nuDraft)
  expect(JSON.stringify(before)).toBe(original)
  correct()
  const doc = readRepositoryDocument()
  const backup = repositoryToBackupV9(doc)
  expect(backup.cards.statements[0]).toMatchObject({ dueMonth: '2026-10', totalCents: 5000, paidAt: '2026-10-08T18:45:24.000Z', charges: [{ id: 'hering-1', installmentNumber: 1, spendingMonth: '2026-09' }] })
  expect(backup.cards.charges.find((row) => row.id === 'hering-2')).toMatchObject({ dueMonth: '2026-11', spendingMonth: '2026-10', installmentNumber: 2 })
  expect(backup.cards.charges.find((row) => row.id === 'umbro-1')).toMatchObject({ dueMonth: '2026-10', spendingMonth: '2026-10', installmentNumber: 1 })
  expect(inspectBackupPayload(backup).issues.filter((issue) => issue.severity === 'error')).toEqual([])
  const restored = backupV9ToRepository(backup)
  expect(restored.collections.cardAccounts).toEqual(doc.collections.cardAccounts)
  writeRepositoryDocument(restored)
  const app = renderHook(() => useFinancas())
  const rows = cardEntriesForCycle(app.result.current.cards.entries, app.result.current.cards.paidInvoices, app.result.current.cards.accounts, '2026-10')
  expect(rows.filter((row) => row.cycle === 'current').map((row) => row.id).sort()).toEqual(['hering-2', 'umbro-1'])
  expect(rows.filter((row) => row.cycle === 'next').map((row) => row.id).sort()).toEqual(['hering-3', 'umbro-2'])
  expect(calculateCreditCardSummary(rows, app.result.current.cards.settings).currentTotal).toBeCloseTo(173.30)
  expect(app.result.current.cardCycleAccounting.invoiceFormedByCycle).toMatchObject({ personalTotal: 173.30, dueMonths: ['2026-10', '2026-11'], amountKnown: true })
  act(() => expect(app.result.current.cards.updateEntry('umbro-2', { amount: 80, personalAmount: 80 })).toBe(true))
  expect(app.result.current.nextCycleAllocation).toMatchObject({ invoice: 130, invoiceKnown: true })
  expect(app.result.current.financialCycle.nextInvoicePersonal).toBe(130)
  expect(app.result.current.cardCycleAccounting.invoiceFormedByCycle.personalTotal).toBeCloseTo(173.30)
})

it('paga ML em outubro, preserva consulta e fecha somente as faturas do calendário de cada cartão', () => {
  seed(); correct()
  const app = renderHook(() => useFinancas())
  act(() => expect(app.result.current.cards.payInvoice('ml', repositoryRevision()).ok).toBe(true))
  const rows = () => cardEntriesForCycle(app.result.current.cards.entries, app.result.current.cards.paidInvoices, app.result.current.cards.accounts, app.result.current.activeCycle.month)
  expect(rows().find((row) => row.id === 'umbro-1')).toMatchObject({ cycle: 'current', dueMonth: '2026-10', paidAt: expect.any(String) })
  expect(rows().find((row) => row.id === 'umbro-2')).toMatchObject({ cycle: 'next', dueMonth: '2026-11' })
  act(() => expect(app.result.current.cards.payInvoice('nu', repositoryRevision()).ok).toBe(true))
  expect(app.result.current.cards.paidInvoices.find((row) => row.accountId === 'nu' && row.dueMonth === '2026-11')).toMatchObject({ total: 50 })
  expect(new Set(app.result.current.cards.paidInvoices.map((row) => row.id)).size).toBe(app.result.current.cards.paidInvoices.length)
  act(() => expect(app.result.current.closeCurrentMonth('2026-10', '', { payInvoice: true, expectedRevision: repositoryRevision() }).ok).toBe(true))
  expect(app.result.current.activeCycle.month).toBe('2026-11')
  expect(app.result.current.cards.paidInvoices.map((row) => row.accountId + ':' + row.dueMonth).sort()).toEqual(['ml:2026-10', 'nu:2026-10', 'nu:2026-11'])
  expect(rows().find((row) => row.id === 'umbro-2')).toMatchObject({ cycle: 'current', dueMonth: '2026-11', paidAt: undefined })
  expect(rows().find((row) => row.id === 'hering-3')).toMatchObject({ cycle: 'current', dueMonth: '2026-12', paidAt: undefined })
  const doc = readRepositoryDocument()
  const onlyML = { ...doc, collections: { ...doc.collections, cardPaidInvoices: app.result.current.cards.paidInvoices.filter((row) => row.accountId === 'ml') } }
  expect(historyCorrectionRows(onlyML, app.result.current.history.snapshots[0].id).some((row) => row.field === 'cardPersonalTotal')).toBe(false)
})

it('recusa colisão com fatura paga, revisão desatualizada e falha de gravação sem aplicar parcialmente', () => {
  seed()
  expect(() => reviewCardCalendar(readRepositoryDocument(), { ...nuDraft, includePaidInvoices: false })).toThrow('colide')
  const revision = repositoryRevision()
  expect(saveCardCalendar(mlDraft, revision).ok).toBe(true)
  const current = repositoryRevision()
  expect(saveCardCalendar(nuDraft, revision)).toMatchObject({ ok: false, reason: 'conflict' })
  expect(repositoryRevision()).toBe(current)
  vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Sem espaço') })
  expect(saveCardCalendar(nuDraft, current)).toMatchObject({ ok: false, reason: 'write_failed' })
  expect(repositoryRevision()).toBe(current)
})

it('importação e mudança de cartão mantêm a competência com meses de vencimento diferentes', () => {
  seed(); correct()
  const app = renderHook(() => useFinancas())
  const account = app.result.current.cards.accounts.find((row) => row.id === 'ml')!
  const review = reviewCardImport(parseSpreadsheetReport('Descrição\tData\tCartão\tFatura\tÉ meu\nCompra extra\t08/10\tML\t25,00\t25,00'), app.result.current.cards.entries, account, '2026-10', false)
  act(() => expect(applyCardImport(review, repositoryRevision()).ok).toBe(true))
  const purchase = app.result.current.cards.entries.find((row) => row.description === 'Compra extra')!
  expect(purchase).toMatchObject({ dueMonth: '2026-10', spendingMonth: '2026-10' })
  act(() => expect(app.result.current.cards.updateEntry(purchase.id, { accountId: 'nu' })).toBe(true))
  expect(app.result.current.cards.entries.find((row) => row.id === purchase.id)).toMatchObject({ dueMonth: '2026-11', spendingMonth: '2026-10', accountId: 'nu' })
  act(() => expect(app.result.current.cards.addEntry({ accountId: 'ml', cardName: 'ML', cycle: 'current', dueMonth: '2026-10', description: 'Assinatura ML', purchaseDate: '08/10', amount: 10, personalAmount: 10, remainingAmount: 0, isRecurring: true })).toBe(true))
  expect(app.result.current.cards.entries.find((row) => row.description === 'Assinatura ML' && row.cycle === 'next')).toMatchObject({ dueMonth: '2026-11', spendingMonth: '2026-11', purchaseDate: '08/11' })
})

it('reconcilia o caixa legado, acompanha novas compras e permite corrigir novamente sem duplicar a diferença', () => {
  seed()
  const source = readRepositoryDocument()
  const originalLegacy = { id: 'legacy-oct', accountId: null, dueMonth: '2026-10', total: 1000, personalTotal: 1000, paidAt: '2026-09-27T12:00:00Z', spending: [] }
  writeRepositoryDocument({ ...source, collections: { ...source.collections, cardPaidInvoices: [...source.collections.cardPaidInvoices as object[], originalLegacy] } })
  correct()
  const app = renderHook(() => useFinancas())
  expect(app.result.current.cardCycleAccounting.invoiceThisCycle).toMatchObject({ personalTotal: 1173.30, paid: false, amountKnown: true })
  const originalAfter = app.result.current.cards.paidInvoices.find((row) => row.id === 'legacy-oct')!
  expect(originalAfter).toMatchObject(originalLegacy)
  act(() => expect(app.result.current.cards.addEntry({ accountId: 'ml', cardName: 'ML', cycle: 'current', dueMonth: '2026-10', description: 'Compra depois do ajuste', purchaseDate: '08/10', amount: 25, personalAmount: 25, remainingAmount: 0 })).toBe(true))
  expect(app.result.current.cardCycleAccounting.invoiceThisCycle.personalTotal).toBeCloseTo(1198.30)
  act(() => expect(saveCardCalendar({ ...mlDraft, openDueMonth: '2026-11', dueMonthOffset: 1, reason: 'Revisão do calendário ML' }, repositoryRevision()).ok).toBe(true))
  expect(app.result.current.cardCycleAccounting.invoiceThisCycle.personalTotal).toBe(1050)
  const backup = repositoryToBackupV9(readRepositoryDocument())
  expect(inspectBackupPayload(backup).issues.filter((issue) => issue.severity === 'error')).toEqual([])
  expect(repositoryToBackupV9(backupV9ToRepository(backup)).cards.statements).toEqual(backup.cards.statements)
})
