import { useCallback, useEffect, useMemo, useRef } from 'react'
import { readRepositoryDocument, useRepositoryState, type RepositoryDocument } from '../data/repository'
import { runRepositoryCommand, type CommandResult } from '../data/repositoryCommand'
import type {
  CreditCardAccount,
  CreditCardCycle,
  CreditCardEntry,
  CreditCardSettings,
} from '../types'
import {
  advanceCreditCardSettingsCycle,
  buildRemainingInstallmentsAmount,
  calculateCreditCardSummary,
  carryUnappliedCredits,
  describeCardCycles,
  inferDueMonthFromPaymentDate,
  normalizeCreditCardSettings,
  normalizeCardAccount,
  normalizeCreditCardEntry,
  syncGeneratedNextEntries,
  unregisteredCardNames,
} from '../lib/creditCards'
import {
  createPaidInvoiceSnapshot,
  normalizePaidInvoiceSnapshots,
  withCardEntrySpendingMonth,
  type PaidInvoiceSnapshot,
} from '../lib/cardCycleAccounting'
import { addMonths, monthKey, uid } from '../lib/shared'
import { normalizeActiveCycle } from '../lib/activeCycle'

function defaultSettingsForCycle(month: string, dueDay = 5): CreditCardSettings {
  const currentDueMonth = month
  return { paymentDate: `${String(dueDay).padStart(2, '0')}/${currentDueMonth.slice(5)}`,
    currentDueMonth, personalSpendingLimit: 1500 }
}

type EntryWithSpendingMonth = CreditCardEntry & { spendingMonth?: string }

function expectedSpendingMonth(entry: CreditCardEntry, currentDueMonth: string) {
  return entry.cycle === 'current' ? addMonths(currentDueMonth, -1) : currentDueMonth
}

function hasExpectedSpendingMonth(entry: CreditCardEntry, currentDueMonth: string) {
  return (entry as EntryWithSpendingMonth).spendingMonth === expectedSpendingMonth(entry, currentDueMonth)
}

function normalizeEntryForDueMonth(entry: CreditCardEntry, currentDueMonth: string): CreditCardEntry {
  const spendingMonth = (entry as EntryWithSpendingMonth).spendingMonth
  const normalized = normalizeCreditCardEntry(entry)
  const withStoredMonth = spendingMonth
    ? ({ ...normalized, spendingMonth } as CreditCardEntry)
    : normalized
  return withCardEntrySpendingMonth(withStoredMonth, currentDueMonth)
}

function normalizeEntriesForDueMonth(entries: CreditCardEntry[], currentDueMonth: string) {
  return entries.map((entry) => normalizeEntryForDueMonth(entry, currentDueMonth))
}

function syncEntriesForDueMonth(entries: CreditCardEntry[], currentDueMonth: string) {
  const normalized = normalizeEntriesForDueMonth(entries, currentDueMonth)
  // A próxima fatura é formada no mês em que a fatura atual vence.
  return normalizeEntriesForDueMonth(
    syncGeneratedNextEntries(normalized, currentDueMonth),
    currentDueMonth,
  )
}

export function payInvoiceInDocument(
  document: RepositoryDocument,
  expectedDueMonth: string,
): RepositoryDocument | null {
  const active = normalizeActiveCycle(document.collections.activeCycle as Parameters<typeof normalizeActiveCycle>[0])
  const settings = normalizeCreditCardSettings(
    (document.collections.cardSettings as CreditCardSettings | undefined) ??
      defaultSettingsForCycle(active.month, active.cardDueHintDay),
  )
  const dueMonth = settings.currentDueMonth ?? inferDueMonthFromPaymentDate(settings.paymentDate)
  if (dueMonth !== expectedDueMonth) return null
  const rawEntries = document.collections.cardEntries
  const entries = normalizeEntriesForDueMonth(
    Array.isArray(rawEntries) ? rawEntries as CreditCardEntry[] : [], dueMonth,
  )
  const paidInvoices = normalizePaidInvoiceSnapshots(document.collections.cardPaidInvoices)
  if (paidInvoices.some((item) => item.dueMonth === dueMonth)) return null
  const paidSummary = calculateCreditCardSummary(entries, settings)
  const snapshot = createPaidInvoiceSnapshot({
    entries, currentDueMonth: dueMonth,
    total: paidSummary.currentTotal, personalTotal: paidSummary.currentPersonalTotal,
  })
  const nextSettings = advanceCreditCardSettingsCycle(settings)
  const nextDueMonth = nextSettings.currentDueMonth ?? inferDueMonthFromPaymentDate(nextSettings.paymentDate)
  const syncedEntries = syncEntriesForDueMonth(entries, dueMonth)
  const carriedCredits = carryUnappliedCredits(syncedEntries).map((credit) =>
    normalizeEntryForDueMonth(credit, nextDueMonth),
  )
  const newCurrentEntries = syncedEntries
    .filter((entry) => entry.cycle === 'next')
    .map((entry) => normalizeEntryForDueMonth({
      ...entry, id: uid(), cycle: 'current', autoGenerated: false, sourceEntryId: undefined,
    }, nextDueMonth))
  return {
    ...document,
    collections: {
      ...document.collections,
      cardPaidInvoices: [...paidInvoices, snapshot].sort((a, b) => a.paidAt.localeCompare(b.paidAt)),
      cardEntries: syncEntriesForDueMonth([...newCurrentEntries, ...carriedCredits], nextDueMonth),
      cardSettings: nextSettings,
    },
  }
}

/**
 * Cada cartão passou a ter fechamento e vencimento próprios. Na primeira carga,
 * os cartões que já apareciam nos lançamentos são cadastrados herdando o
 * vencimento global antigo — nada se perde e nada precisa ser redigitado.
 */
export function useCreditCards(activeCycleMonth = monthKey(), cardDueHintDay = 5) {
  const [storedSettings, setSettingsRaw] = useRepositoryState<CreditCardSettings>(
    'cardSettings',
    () => defaultSettingsForCycle(activeCycleMonth, cardDueHintDay),
  )
  const settings = useMemo(() => normalizeCreditCardSettings(storedSettings), [storedSettings])
  useEffect(() => {
    if (readRepositoryDocument().collections.cardSettings === undefined) {
      setSettingsRaw(defaultSettingsForCycle(activeCycleMonth, cardDueHintDay))
    }
  }, [activeCycleMonth, cardDueHintDay, setSettingsRaw])
  const currentDueMonth =
    settings.currentDueMonth ?? inferDueMonthFromPaymentDate(settings.paymentDate)

  const [storedEntries, setEntries] = useRepositoryState<CreditCardEntry[]>('cardEntries', [])
  const entries = useMemo(
    () =>
      Array.isArray(storedEntries)
        ? normalizeEntriesForDueMonth(storedEntries, currentDueMonth)
        : [],
    [currentDueMonth, storedEntries],
  )

  const [storedAccounts, setStoredAccounts] = useRepositoryState<CreditCardAccount[]>(
    'cardAccounts',
    [],
  )
  const accounts = useMemo(
    () => (Array.isArray(storedAccounts) ? storedAccounts.map(normalizeCardAccount) : []),
    [storedAccounts],
  )

  const [storedPaidInvoices] = useRepositoryState<PaidInvoiceSnapshot[]>(
    'cardPaidInvoices',
    [],
  )
  const paidInvoices = useMemo(
    () => normalizePaidInvoiceSnapshots(storedPaidInvoices),
    [storedPaidInvoices],
  )
  const lastPaidInvoice = paidInvoices.length ? paidInvoices[paidInvoices.length - 1] : null

  // Repara backups antigos e também a migração anterior que tentou inferir o mês
  // pela data da compra. A fronteira correta é o bucket da fatura: current = ciclo
  // anterior ao vencimento; next = ciclo do vencimento atual.
  useEffect(() => {
    if (
      !Array.isArray(storedEntries) ||
      storedEntries.every((entry) => hasExpectedSpendingMonth(entry, currentDueMonth))
    ) {
      return
    }
    setEntries((prev) => normalizeEntriesForDueMonth(prev, currentDueMonth))
  }, [currentDueMonth, setEntries, storedEntries])

  // A geração da próxima fatura roda a cada mutação, mas dados que chegam
  // prontos (backup importado, outro dispositivo) nunca passaram por uma.
  const syncedOnMount = useRef(false)
  useEffect(() => {
    if (syncedOnMount.current || entries.length === 0) return
    syncedOnMount.current = true
    setEntries((prev) => syncEntriesForDueMonth(prev, currentDueMonth))
  }, [currentDueMonth, entries.length, setEntries])

  const addEntry = useCallback(
    (entry: Omit<CreditCardEntry, 'id'>) => {
      return setEntries((prev) => {
        const nextEntries = [
          ...normalizeEntriesForDueMonth(prev, currentDueMonth),
          normalizeEntryForDueMonth({ ...entry, id: uid() }, currentDueMonth),
        ]
        return entry.cycle === 'current'
          ? syncEntriesForDueMonth(nextEntries, currentDueMonth)
          : nextEntries
      })
    },
    [currentDueMonth, setEntries],
  )

  const updateEntry = useCallback(
    (id: string, patch: Partial<Omit<CreditCardEntry, 'id'>>) => {
      return setEntries((prev) => {
        const normalizedPrev = normalizeEntriesForDueMonth(prev, currentDueMonth)
        const target = normalizedPrev.find((entry) => entry.id === id)
        if (!target) return prev

        // Editar um lançamento gerado automaticamente o torna manual,
        // para a edição não ser descartada na próxima sincronização.
        const effectivePatch =
          target.cycle === 'next' && target.autoGenerated
            ? { ...patch, autoGenerated: false }
            : patch
        const nextEntries = normalizedPrev.map((entry) =>
          entry.id === id
            ? normalizeEntryForDueMonth({ ...entry, ...effectivePatch }, currentDueMonth)
            : entry,
        )

        return target.cycle === 'current'
          ? syncEntriesForDueMonth(nextEntries, currentDueMonth)
          : nextEntries
      })
    },
    [currentDueMonth, setEntries],
  )

  const removeEntry = useCallback(
    (id: string) => {
      return setEntries((prev) => {
        const normalizedPrev = normalizeEntriesForDueMonth(prev, currentDueMonth)
        const target = normalizedPrev.find((entry) => entry.id === id)
        const nextEntries = normalizedPrev.filter((entry) => entry.id !== id)
        return target?.cycle === 'current'
          ? syncEntriesForDueMonth(nextEntries, currentDueMonth)
          : nextEntries
      })
    },
    [currentDueMonth, setEntries],
  )

  const replaceEntries = useCallback(
    (cycle: CreditCardCycle, incoming: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      return setEntries((prev) => {
        const nextEntries = [
          ...normalizeEntriesForDueMonth(prev, currentDueMonth).filter(
            (entry) => entry.cycle !== cycle,
          ),
          ...incoming.map((entry) =>
            normalizeEntryForDueMonth({ ...entry, cycle, id: uid() }, currentDueMonth),
          ),
        ]
        return cycle === 'current'
          ? syncEntriesForDueMonth(nextEntries, currentDueMonth)
          : nextEntries
      })
    },
    [currentDueMonth, setEntries],
  )

  const appendEntries = useCallback(
    (cycle: CreditCardCycle, incoming: Omit<CreditCardEntry, 'id' | 'cycle'>[]) => {
      return setEntries((prev) => {
        const nextEntries = [
          ...normalizeEntriesForDueMonth(prev, currentDueMonth),
          ...incoming.map((entry) =>
            normalizeEntryForDueMonth({ ...entry, cycle, id: uid() }, currentDueMonth),
          ),
        ]
        return cycle === 'current'
          ? syncEntriesForDueMonth(nextEntries, currentDueMonth)
          : nextEntries
      })
    },
    [currentDueMonth, setEntries],
  )

  const anticipateInstallments = useCallback(
    (id: string, count: number) => {
      return setEntries((prev) => {
        const normalizedPrev = normalizeEntriesForDueMonth(prev, currentDueMonth)
        const entry = normalizedPrev.find((item) => item.id === id)
        if (
          !entry ||
          entry.cycle !== 'current' ||
          !entry.installmentCurrent ||
          !entry.installmentTotal
        ) {
          return prev
        }

        const current = entry.installmentCurrent
        const total = entry.installmentTotal
        const quantity = Math.min(Math.max(1, Math.floor(count)), total - current)
        if (quantity < 1) return prev

        // Cada parcela antecipada vira um lançamento próprio na mesma competência.
        const anticipated = Array.from({ length: quantity }, (_, index) => {
          const installment = current + index + 1
          return normalizeEntryForDueMonth(
            {
              ...entry,
              id: uid(),
              installmentCurrent: installment,
              remainingAmount:
                installment === current + quantity
                  ? buildRemainingInstallmentsAmount(entry.amount, installment, total)
                  : 0,
            },
            currentDueMonth,
          )
        })

        return syncEntriesForDueMonth(
          [
            ...normalizedPrev.map((item) =>
              item.id === id ? { ...item, remainingAmount: 0 } : item,
            ),
            ...anticipated,
          ],
          currentDueMonth,
        )
      })
    },
    [currentDueMonth, setEntries],
  )

  const payInvoice = useCallback((expectedRevision?: string | null): CommandResult => {
    return runRepositoryCommand({
      id: `pay-invoice:${currentDueMonth}`,
      expectedRevision,
      apply: (document) => payInvoiceInDocument(document, currentDueMonth),
    })
  }, [
    currentDueMonth,
  ])

  const setSettings = useCallback(
    (next: CreditCardSettings) => {
      return setSettingsRaw(normalizeCreditCardSettings(next))
    },
    [setSettingsRaw],
  )

  const setDueMonth = useCallback((month: string, expectedRevision?: string | null) =>
    runRepositoryCommand({ id: uid(), expectedRevision, apply: (document) => {
      if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)) return null
      const previous = normalizeCreditCardSettings(
        (document.collections.cardSettings as CreditCardSettings | undefined) ??
          defaultSettingsForCycle(activeCycleMonth, cardDueHintDay))
      const dueDay = Number(previous.paymentDate.slice(0, 2)) || 5
      const entries = Array.isArray(document.collections.cardEntries)
        ? document.collections.cardEntries as CreditCardEntry[] : []
      return { ...document, collections: { ...document.collections,
        cardSettings: { ...previous, currentDueMonth: month,
          paymentDate: `${String(dueDay).padStart(2, '0')}/${month.slice(5)}` },
        cardEntries: normalizeEntriesForDueMonth(entries, month),
      } }
    } }).ok,
  [activeCycleMonth, cardDueHintDay])

  const addAccount = useCallback(
    (input: { name: string; closingDay: number; dueDay: number; limit?: number }) => {
      const trimmed = input.name.trim()
      if (!trimmed) return
      setStoredAccounts((prev) => [
        ...(Array.isArray(prev) ? prev : []),
        normalizeCardAccount({ ...input, name: trimmed, id: uid() }),
      ])
    },
    [setStoredAccounts],
  )

  const updateAccount = useCallback(
    (id: string, patch: Partial<Omit<CreditCardAccount, 'id'>>) => {
      setStoredAccounts((prev) =>
        prev.map((account) =>
          account.id === id ? normalizeCardAccount({ ...account, ...patch }) : account,
        ),
      )
    },
    [setStoredAccounts],
  )

  const removeAccount = useCallback(
    (id: string) => setStoredAccounts((prev) => prev.filter((account) => account.id !== id)),
    [setStoredAccounts],
  )

  const summary = useMemo(() => calculateCreditCardSummary(entries, settings), [entries, settings])
  const cycles = useMemo(() => describeCardCycles(accounts, summary), [accounts, summary])
  const unregistered = useMemo(() => unregisteredCardNames(entries, accounts), [entries, accounts])

  return {
    entries,
    settings,
    accounts,
    cycles,
    unregistered,
    summary,
    paidInvoices,
    lastPaidInvoice,
    addAccount,
    updateAccount,
    removeAccount,
    addEntry,
    updateEntry,
    removeEntry,
    replaceEntries,
    appendEntries,
    anticipateInstallments,
    payInvoice,
    setSettings,
    setDueMonth,
  }
}
